### ISSUE TITLE
error after update to 0.3.0

### ISSUE THREAD

**Issue by aGiant** [reinforceio/tensorforce#199]
After update to 0.3.0, this import did not work any more:

from tensorforce.core.networks import layered_network_builder
ImportError: cannot import name layered_network_builder

**Comment by AlexKuhnle** [comment]
Hi @aGiant,

Yes, this part changed quite a bit with the update (sorry for all the breaking changes in this one). To get started, [this part](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/base_agent_test.py#L131) of the tests hopefully helps. We will also update the introduction blogpost over the weekend.

**Comment by aGiant** [comment]
I had more errors using 
agent = DQNAgent(states_spec=dict(shape=(len(cols),), type='float'),
				 actions_spec=dict( num_actions=N_acts+Z, type='int'),
				 network_spec=network_spec,
				 config=config)

Then:
File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/dqn_agent.py", line 160, in __init__
    super(DQNAgent, self).__init__(states_spec, actions_spec, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/memory_agent.py", line 58, in __init__
    actions_spec=self.actions_spec
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/memories/memory.py", line 104, in from_spec
    kwargs=kwargs
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 167, in get_object
    return obj(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/memories/replay.py", line 33, in __init__
    self.states = {name: np.zeros((capacity,) + tuple(state['shape']), dtype=util.np_dtype(state['type'])) for name, state in states_spec.items()}
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/memories/replay.py", line 33, in <dictcomp>
    self.states = {name: np.zeros((capacity,) + tuple(state['shape']), dtype=util.np_dtype(state['type'])) for name, state in states_spec.items()}
TypeError: 'float' object cannot be interpreted as an index

**Comment by AlexKuhnle** [comment]
Do you set the memory capacity to `1e[N]`? This probably causes the float error. Could probably add an int conversion, if this shortform is desired.

**Comment by aGiant** [comment]
I just used the default value of memory capacity.

**Comment by AlexKuhnle** [comment]
Then it seems the code is using the format I just said... :-)  Will have a look.

**Comment by AlexKuhnle** [comment]
Have you updated to the latest version? I think the default values are all set correctly, unless I'm overlooking something...

**Comment by aGiant** [comment]
Yes, it's version 0.3.0.

**Comment by aGiant** [comment]
I got more errors...
Settings:
# Create a Trust Region Policy Optimization agent
config_naf = Configuration(
    batch_size=batch_size, #update_frequency = 96, #epochs=10,
	learning_rate=0.008,
	discount = gold_rate, #0.99, #distributed = True,
	normalize_rewards=True, use_target_network=True,
	#memory='prioritized_replay', #min_replay_size=240,
	#first_update=10000, #repeat_update=960,
    memory_capacity=3000000,#normalize_rewards=True,
	#target_update_frequency = 48,
	#update_target_weight = 0.5,
	#keep_last = False,
	#optimizer = 'adam',
	#clip_loss = 0.2,
	#baseline = 'linear',
	#gae_rewards = True, gae_lambda = 0.9,
	baseline =  {
    "type": "mlp",#"linear", #
    "sizes": [1280, 640, 320] ,#, 160 80, 40],
    "epochs": 1,
    "update_batch_size" : batch_size,
    "learning_rate": 0.01
  	},
	exploration = {
		"type": "ornstein_uhlenbeck",
        "sigma":0.1,
        "mu":0,
        "theta":0.1}
	#,
	#optimizer = {
    #"type": "rmsprop",
    #"momentum": 0.9,
    #"epsilon": 0.01
  	#}#
)
states = dict(shape=(len(cols),), type='float')
actions=dict(continuous=True, shape=(len(action_names),), type = 'float')
agent = NAFAgent(states_spec = states, actions_spec = actions, network_spec=network, config=config_naf)

Errors:
Traceback (most recent call last):
  File "tensorforce_trading_naf_2.py", line 138, in <module>
    agent = NAFAgent(states_spec = states, actions_spec = actions, network_spec=network, config=config_naf) # config_naf
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/naf_agent.py", line 111, in __init__
    super(NAFAgent, self).__init__(states_spec, actions_spec, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/memory_agent.py", line 51, in __init__
    super(MemoryAgent, self).__init__(states_spec, actions_spec, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/agent.py", line 177, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/naf_agent.py", line 118, in initialize_model
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/q_naf_model.py", line 47, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/q_model.py", line 54, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/distribution_model.py", line 98, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 181, in __init__
    deterministic=self.deterministic
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 592, in create_output_operations
    reward=reward
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 261, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/q_model.py", line 128, in tf_optimization
    optimization = super(QModel, self).tf_optimization(states, internals, actions, terminal, reward)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 516, in tf_optimization
    return self.optimizer.minimize(**optimizer_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/optimizer.py", line 81, in minimize
    deltas = self.step(time=time, variables=variables, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 261, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/tf_optimizer.py", line 82, in tf_step
    applied = self.optimizer.minimize(loss=loss, var_list=variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 325, in minimize
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 132, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 140, in custom_getter
    variable = getter(name=name, **kwargs)  # Top-level, hence no 'registered'
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable optimization/step/optimization/step/loss/loss-per-instance/apply_2/W/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

originally defined at:
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 172, in __init__
    self.optimizer = Optimizer.from_spec(spec=config.optimizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/optimizer.py", line 102, in from_spec
    kwargs=kwargs
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 167, in get_object
    return obj(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/tf_optimizer.py", line 45, in wrapper
    return TFOptimizer(optimizer=optimizer, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/tf_optimizer.py", line 57, in __init__
    super(TFOptimizer, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/optimizer.py", line 50, in __init__
    custom_getter=custom_getter


originally defined at:
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 151, in __init__
    self.initialize(custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/distribution_model.py", line 102, in initialize
    super(DistributionModel, self).initialize(custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 336, in initialize
    custom_getter_=custom_getter

**Comment by AlexKuhnle** [comment]
Ah, I see, it's not the latest Github commit. We will soon (1-2 days) update to version 0.3.1 which will include the first bug fixes. Sorry for that, all a bit chaotic at the moment after the big change. If you clone the Github version and update it, it should (hopefully) work, same for the other error you just sent (I just fixed that earlier today, I think).

**Comment by aGiant** [comment]
I have cloned github version and it's 0.3.0.

**Comment by michaelschaarschmidt** [comment]
What is the status of this?

**Comment by AlexKuhnle** [comment]
Closed due to lack of activity, and because the problems are likely fixed in recent commits. Please re-open if not.
